In [4]:
a = [2,4,6,8,10]

In [5]:
b = []
for num in a:
    b.append(2*num)
b

[4, 8, 12, 16, 20]

In [6]:
import numpy as np  

//numpy is a pre-defined not a user defined

In [7]:
a = np.array( [2,3,4,5,6,9,10])

In [8]:
type(a)

numpy.ndarray

In [9]:
3*a

array([ 6,  9, 12, 15, 18, 27, 30])

In [10]:
data1 = np.arange(10)
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
data1.ndim

1

matrix are tensor in machine learning 
vector 01 dimension tensor hai

In [12]:
data = np.random.randn(2,3)
data

array([[ 0.17924776, -0.45195559,  0.19253125],
       [ 0.52200258, -1.58240449,  1.4893371 ]])

In [13]:
data.shape

(2, 3)

there are 2 rows
there are 3 columns

In [14]:
b= np.array([[[100]]])

In [15]:
b.ndim

3

No of bracket shows the dimensions

In [16]:
b.shape

(1, 1, 1)

In [17]:
_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [18]:
_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [19]:
threeD = np.arange(64).reshape(4,4,4)

In [20]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [21]:
threeD = np.arange(30).reshape(3,5,2) #3 is height or depth
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [22]:
threeD = np.arange(30).reshape(5,3,2)
threeD

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [23]:
threeD.ndim

3

In [24]:
threeD = np.arange(30).reshape(2,5,3)
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [25]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[7,8,9],[4,3,2]])

In [26]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 3, 2]])

In [28]:
m1.shape < m2.shape

False

In [29]:
m1.shape==m2.shape

True

In [30]:
m1.shape!=m2.shape

False

In [31]:
m1+m2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [13, 13, 13]])

In [32]:
m1-m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 5,  7,  9]])

In [33]:
#shape same thatswhy il will multiply
m1*m2

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72],
       [36, 30, 22]])

In [35]:
m1/m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889],
       [2.25      , 3.33333333, 5.5       ]])

This is the element wise operation

In [36]:
m1.shape

(4, 3)

In [48]:
m1@m3

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [49]:
m1*m2

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72],
       [36, 30, 22]])

In [37]:
m2.shape

(4, 3)

In [38]:
m3 = np.arange(12).reshape(3,4)

In [39]:
m3.shape

(3, 4)

In [53]:
m1.dot(m3)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [56]:
#  if you change data type of Any variable
a = np.array([33.,44,66],dtype="float32")

In [57]:
a

array([33., 44., 66.], dtype=float32)

agr ek bh no float mai hogya to sare automatic float mai hojangy

In [43]:
a = np.array([33.,44,66],dtype=np.float32)

In [44]:
a

array([33., 44., 66.], dtype=float32)

In [45]:
b = np.asarray(a,np.int32)

In [58]:
b

array([33, 44, 66])

for changing data of an array

In [59]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [65]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
np.ones((3,4))*2+1/4

array([[2.25, 2.25, 2.25, 2.25],
       [2.25, 2.25, 2.25, 2.25],
       [2.25, 2.25, 2.25, 2.25]])

In [70]:
# you can multiple like this
m1 = np.full((3,4),7)
m1

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [71]:
m2 = np.ones_like(m1)

In [72]:
m2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [73]:
alist = [1,2,3,4,5,6,7,8]
alist[4]

5

In [117]:
type(alist)

list

In [116]:
type(alist[2:4])

list

indexing kro to value ati ha
slicing kro to list ati ha

In [118]:
type(alist[4])

int

In [78]:
td = np.arange(36).reshape(6,6)

In [79]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [80]:
td[2,3] 

15

In [81]:
#td[r,c]
#td[--, --]
a = td[2:5,2:4]

In [82]:
a

array([[14, 15],
       [20, 21],
       [26, 27]])