# Boolean Indexing

In [165]:
import numpy as np
name=np.array(['haziq','mustafa','pappu','haziq','abbalog','haziq','pappu'])

In [166]:
data=np.random.randn(7,4)

In [167]:
name

array(['haziq', 'mustafa', 'pappu', 'haziq', 'abbalog', 'haziq', 'pappu'],
      dtype='<U7')

In [168]:
data

array([[-0.3286242 , -0.86988096,  0.33506756,  0.04235412],
       [ 1.20012548, -1.8930027 , -0.55567914, -0.28999251],
       [ 0.65611084,  0.98519984,  0.9004534 ,  0.89204589],
       [ 1.36037796,  0.58836819,  1.42746352, -1.06242815],
       [ 1.43318498, -0.41813356, -2.76298552,  0.00427787],
       [ 0.88580092,  0.82184738,  0.05252086,  1.38485491],
       [-0.58403057,  0.43784365,  1.19571916,  1.11262519]])

In [169]:
name=='haziq'

array([ True, False, False,  True, False,  True, False])

In [170]:
# they define that name is in this  index num
data[name== 'haziq']

array([[-0.3286242 , -0.86988096,  0.33506756,  0.04235412],
       [ 1.36037796,  0.58836819,  1.42746352, -1.06242815],
       [ 0.88580092,  0.82184738,  0.05252086,  1.38485491]])

In [171]:
# they define where the (name==haziq) is not in index num 
data[name!='haziq']

array([[ 1.20012548, -1.8930027 , -0.55567914, -0.28999251],
       [ 0.65611084,  0.98519984,  0.9004534 ,  0.89204589],
       [ 1.43318498, -0.41813356, -2.76298552,  0.00427787],
       [-0.58403057,  0.43784365,  1.19571916,  1.11262519]])

In [172]:
data[name=='haziq',2:]

array([[ 0.33506756,  0.04235412],
       [ 1.42746352, -1.06242815],
       [ 0.05252086,  1.38485491]])

In [173]:
data

array([[-0.3286242 , -0.86988096,  0.33506756,  0.04235412],
       [ 1.20012548, -1.8930027 , -0.55567914, -0.28999251],
       [ 0.65611084,  0.98519984,  0.9004534 ,  0.89204589],
       [ 1.36037796,  0.58836819,  1.42746352, -1.06242815],
       [ 1.43318498, -0.41813356, -2.76298552,  0.00427787],
       [ 0.88580092,  0.82184738,  0.05252086,  1.38485491],
       [-0.58403057,  0.43784365,  1.19571916,  1.11262519]])

In [174]:
data[name == 'haziq', 2:]

array([[ 0.33506756,  0.04235412],
       [ 1.42746352, -1.06242815],
       [ 0.05252086,  1.38485491]])

In [175]:
data[name=='haziq',3]

array([ 0.04235412, -1.06242815,  1.38485491])

In [176]:
name != 'haziq'

array([False,  True,  True, False,  True, False,  True])

In [177]:
data[~(name=='haziq')]

array([[ 1.20012548, -1.8930027 , -0.55567914, -0.28999251],
       [ 0.65611084,  0.98519984,  0.9004534 ,  0.89204589],
       [ 1.43318498, -0.41813356, -2.76298552,  0.00427787],
       [-0.58403057,  0.43784365,  1.19571916,  1.11262519]])

In [178]:
cond=name=='haziq'

In [179]:
data[~cond]

array([[ 1.20012548, -1.8930027 , -0.55567914, -0.28999251],
       [ 0.65611084,  0.98519984,  0.9004534 ,  0.89204589],
       [ 1.43318498, -0.41813356, -2.76298552,  0.00427787],
       [-0.58403057,  0.43784365,  1.19571916,  1.11262519]])

In [180]:
mask=(name=='haziq')|(name=='abbalog')

In [181]:
mask

array([ True, False, False,  True,  True,  True, False])

In [182]:
data[mask]

array([[-0.3286242 , -0.86988096,  0.33506756,  0.04235412],
       [ 1.36037796,  0.58836819,  1.42746352, -1.06242815],
       [ 1.43318498, -0.41813356, -2.76298552,  0.00427787],
       [ 0.88580092,  0.82184738,  0.05252086,  1.38485491]])

In [183]:
data<0

array([[ True,  True, False, False],
       [False,  True,  True,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [False,  True,  True, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [184]:
data[data<0]

array([-0.3286242 , -0.86988096, -1.8930027 , -0.55567914, -0.28999251,
       -1.06242815, -0.41813356, -2.76298552, -0.58403057])

In [185]:
data[data<0]=0

In [186]:
data

array([[0.        , 0.        , 0.33506756, 0.04235412],
       [1.20012548, 0.        , 0.        , 0.        ],
       [0.65611084, 0.98519984, 0.9004534 , 0.89204589],
       [1.36037796, 0.58836819, 1.42746352, 0.        ],
       [1.43318498, 0.        , 0.        , 0.00427787],
       [0.88580092, 0.82184738, 0.05252086, 1.38485491],
       [0.        , 0.43784365, 1.19571916, 1.11262519]])

# Fancy indexing


In [187]:
arr=np.empty((8, 4))

In [188]:
for i in range(8):
    arr[i]=i

In [189]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [190]:
arr[4]

array([4., 4., 4., 4.])

In [191]:
arr[[4,6]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [192]:
arr[[4,3],2:]

array([[4., 4.],
       [3., 3.]])

In [193]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [194]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [195]:
arr=np.arange(32).reshape(8,4)

In [196]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [197]:
arr[[1,5,2,7],[0,3,1,2]]

array([ 4, 23,  9, 30])

In [198]:
#1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],2[0,3,1,2]
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])


# Array Transpose & Swapping Axes

In [199]:
arr = np.arange(15).reshape((3, 5))

In [200]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [201]:
#to convert horizental into verical 
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Universal Functions

In [202]:
arr = np.arange(10)

In [203]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [204]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [205]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [206]:
 x = np.random.randn(8)

In [207]:
 y = np.random.randn(8)


In [208]:
x

array([-1.08127031,  0.58494358,  1.60656924, -1.61108224,  2.85136175,
       -0.26349982,  1.49432577,  1.77927708])

In [209]:
y

array([ 1.19092155, -1.56991033,  1.2246983 ,  0.5660203 , -0.74178024,
        0.35324151, -0.42640074,  0.5757334 ])

In [210]:
np.maximum(x,y)

array([1.19092155, 0.58494358, 1.60656924, 0.5660203 , 2.85136175,
       0.35324151, 1.49432577, 1.77927708])

In [211]:
arr = np.random.randn(7) * 5

In [212]:
arr

array([ 6.46978889, -3.48205948,  1.80420832, -0.15286995, -3.33015682,
       -3.13403076, -2.82979696])

In [213]:
remainder, whole_part = np.modf(arr)

In [214]:
remainder 

array([ 0.46978889, -0.48205948,  0.80420832, -0.15286995, -0.33015682,
       -0.13403076, -0.82979696])

In [215]:
whole_part

array([ 6., -3.,  1., -0., -3., -3., -2.])

In [216]:
arr

array([ 6.46978889, -3.48205948,  1.80420832, -0.15286995, -3.33015682,
       -3.13403076, -2.82979696])

In [217]:
np.sqrt(arr)

C:\Users\haziq\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.54357797,        nan, 1.34320822,        nan,        nan,
              nan,        nan])

In [218]:
np.sqrt(arr,arr)

C:\Users\haziq\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.54357797,        nan, 1.34320822,        nan,        nan,
              nan,        nan])

///////////////////////////////////////////////remain/////////////////////////////////////////////////

Please see table given in book pg 130-131

In [225]:
arr=np.arange(24)

In [224]:
.shape((4,-1))

SyntaxError: invalid syntax (<ipython-input-224-0c67d7cb7d17>, line 1)

In [226]:
arr = np.arange(15).reshape((5, 3))

In [232]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [233]:
ravel=arr.ravel()

In [234]:
flatten=arr.flatten()

In [235]:
ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [236]:
flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [237]:
flatten[2:8]=0

In [240]:
 flatten

array([ 0,  1,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [241]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Concatenating and Splitting Arrays

In [246]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [247]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [248]:
np.concatenate([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [252]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [253]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [254]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [260]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [261]:
splitt =np.arange(1,25).reshape(6,4)
splitt

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [266]:
np.vsplit(splitt,3)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]), array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [267]:
np.hsplit(splitt,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]